FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED = 1

RUN  apt update \
    && apt-get install -y libpq-dev python-dev-is-python3 \
    && sudo apt-get install python3-pip \
    && apt-get install default-libmysqlclient-dev

RUN mkdir /srv/docker-server
ADD . /srv/docker-server

WORKDIR /srv/docker-server/demo_mes

RUN pip install -r requirements.txt

EXPOSE 8000  

CMD ['python', 'manage.py','runserver', '0.0.0.0:8000']  
# ENTRYPOINT ["sh", "./docker-entrypoint.sh"] 